stages:
  - build
  - test
  - package
  - deploy

variables:
  maven_package_cache: ".m2/repository"

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
    - $maven_package_cache
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
    - target/*
  script:
    - mvn compile

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  cache:
    paths:
      - $maven_package_cache
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - target/surefire-reports/*
      - target/site/jacoco/*
  script:
    - mvn test

package:
  stage: package
  tags:
    - docker
  dependencies:
    - build
  cache:
    paths:
      - $maven_package_cache
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - target/*.war
  script:
    - mvn package

deploy_test:
  stage: deploy
  tags:
    - shell
  dependencies:
    - package
  script:
    - docker rm --force tomcat
    - docker image rm --force connect-four
    - docker build -t connect-four .
    - docker run -d --rm --name tomcat -p 8080:8080 connect-four
  when: manual
  environment:
    name: test
    action: start
    url: http://localhost:8080/ConnectFour
    on_stop: stop_test

stop_test:
  stage: deploy
  tags:
    - shell
  environment:
    name: test
    action: stop
  when: manual
  script:
    - docker rm --force tomcat
    - docker image rm --force connect-four