env:
  maven_package_cache: ".m2/repository"

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@main
        run: ls -l && mvn compile

