env:
  maven_package_cache: ".m2/repository"

on: [push]

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
            java-version: '21'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: echo $JAVA_HOME && mvn compile
        with:
          name: artifacts
          path: target/*
